### ISSUE TITLE
gin.mangafox.info problem

### ISSUE THREAD

**Issue by calgara12** [pikax/gin-downloader#9]
Hey, 
just now i encountered the following problem. 

I wanted to iterate through all mangas on mangafox and show further info for each manga. 
Here is the code:
```javascript
gin.mangafox.mangas().then(function (result) {
    result.forEach(function (item) {
        gin.mangafox.info(item.name).then(console.log).catch(console.error);
    })
}).catch( function (err) {
    console.error(err)
});
```
If i run this, i get a lot of errors that say the Manga can't be found.
![error](https://user-images.githubusercontent.com/28657023/27009781-0712f432-4e97-11e7-8d32-afd93092ed56.PNG)

But if i search for the same Manga info manually with:
```javascript
gin.mangafox.info("Yurikuma Arashi").then(console.log);
```
I get the following result: 
![found](https://user-images.githubusercontent.com/28657023/27009794-4cc5da3a-4e97-11e7-85c4-1dc0c75b208c.PNG)

Although some mangas also can't be found with the manual search.

Thanks in advance! :)

**Comment by pikax** [comment]
The issue seems to be an `Error: connect ENOBUFS`.

I just committed and a way to debug those errors, because I catch the exception and throw a generic error.

just update the package, `gin-downloader` uses [debug](https://www.npmjs.com/package/debug) to log errors and such:

to get mangafox errors:
```bash
#windows
set DEBUG=gin-downloader:MangaFox:error 

#linux 
EXPORT DEBUG=gin-downloader:MangaFox:error

#running your file
node index.js 
```


```javascript
gin.mangafox.mangas().then(function (result) { // is returning an array of 19205 items
    result.forEach(function (item) { // you opening/requesting 19205 pages to the server
        gin.mangafox.info(item.name).then(console.log).catch(console.error);
    })
}).catch( function (err) {
    console.error(err)
});
```

What happens is you just maxed out the maximum number of connection nodejs can do. MangaFox already implements some sort of rate limiting, so doing so many requests at same time is overkill, I would recommend getting little tinny lists or use bluebird to only request like 10 or 20 pages at the time.

```javascript

var _ = require('lodash');

var MAX_CHUNK = 10; // 10 mangas at the time

gin.mangafox.mangas().then(function (result) {

  var chunks = _.chunk(result, MAX_CHUNK); // just creating a list of chunks
  var promise = Promise.resolve(console.log('starting %d chunks...', chunks.length));

  chunks.forEach(function (c){
    promise = promise.then(function(){

      let promises = c.map(p=>  gin.mangafox.info(p.name).then(console.log).catch(console.error));

      return Promise.all(promises);
    });

  });

  promise.then(console.log('finished'));

}).catch( function (err) {
  console.error(err)
});
```

Thank you for raising this issue, not sure if I can do something about it in the API.

Let me know if you need any more help

**Comment by calgara12** [comment]
Sorry for the late response, just wanted to thank you, this solution works perfectly!

**Comment by pikax** [comment]
You're welcome :)
